### ISSUE TITLE
Shape height does not prevent block suffocation

### ISSUE THREAD

**Issue by VillainousEater** [ToCraft/woodwalkers-mod#89] opened 2024-05-13 14:00 UTC
### Mod loader

Forge

### Minecraft version

1.20.1

### Woodwalkers version

4.4.2

### CraftedCore version

4.1

### Modloader version

47.2.8

### The latest.log file

https://mclo.gs/dioRi6V

### Issue description

When morphing into a mob shorter than a block, e.g. wolf or fox, and walking under a block (1 block tall ceiling), I begin suffocating and the screen turns black (covered by the block texture) as if I am inside the wall. In reality I am under it.

I specifically chose short mobs to be able to go under blocks. Tried different short mobs, vanilla, to make sure it's not a bug with modded mob.

### Steps to reproduce

1. Morph into small mob (fox, frog, etc)
2. Go under a block
3. Damage is taken due to suffocation

**Comment by ToCraft** [comment] 2024-05-13 14:49
Yeah, I've reworked some background code (and I'm still reworking it).
it was probably caused by me shortening duplicate code. It'll be fixed with the next update.

**Comment by ToCraft** [comment] 2024-05-16 08:10
Fixed as of 4.4.3 :D

**Closed by ToCraft** 2024-05-16 08:10 UTC
Labels: bug
