### ISSUE TITLE
Better Combat Compat

### ISSUE THREAD

**Issue by TWHalikon** [ToCraft/woodwalkers-mod#75] opened 2024-03-14 19:38 UTC
### Describe your idea, include images if necessary

Currently whenever you attack while morphed with better combat you look into the mob head for the combat animation and the hitbox for the weapon is invisible.
![Screenshot](https://github.com/ToCraft/woodwalkers-mod/assets/31938470/a51b9855-8bfe-4160-9188-5d05180fb334)

If possible, it would be great to fix the issue of seeing inside the mob head, I assume this happens because of how better combat does their animations. Also, maybe in the future have it so you can see the weapon being swung in front of the mob and for humanoid mobs (zombie, skeleton, etc) to have combat animations.

**Comment by ToCraft** [comment] 2024-03-15 14:20
It might be a bit complicated to fix this, since it's not caused by woodwalkers but rather by Better Combat. I'll do my best to fix it or send a fix to the Developer of Better Combat.

**Comment by ToCraft** [comment] 2024-06-02 16:24
Alright, I've just managed to write some kind of fix for this- from now on, the Better Combat Animation just won't work in First Person when Woodwalkers is installed. (The Animation still work in third person, where they look way more epic anyway). I know this isn't the best solution, but it's at least playable with both mods installed.

Here's the commit: 9190c6a044e7beca1f4220e370b2b818233dc209

**Closed by ToCraft** 2024-06-02 16:24 UTC
Labels: enhancement
