### ISSUE TITLE
Crash on Startup with latest version (Error code 2)

### ISSUE THREAD

**Issue by IceCubeDragon** [ToCraft/woodwalkers-mod#139] opened 2024-10-07 06:13 UTC
### Mod loader

Forge

### Minecraft version

1.20.1

### Woodwalkers version

5.3.2

### CraftedCore version

5.5

### Modloader version

47.3.0, 47.2.0

### The latest.log file

https://mclo.gs/ogEYlze

### Issue description

Crash on startup with Error Code 2 in Forge, have tried loading in isolation, switching modloader version, and Craftedcore 5.5 works fine on its own

### Steps to reproduce

Crash on startup

**Comment by IceCubeDragon** [comment] 2024-10-07 06:18
Note: after further testing it loads successfully on 5.2, issue happens any version that's 5.3 or 5.3.x

**Comment by ToCraft** [comment] 2024-10-07 07:39
Thanks for reporting, but this issue is a duplicate of https://github.com/ToCraft/woodwalkers-mod/issues/137. I'll close this issue to avoid confusion.

**Closed** 2024-10-07 07:40 UTC
Labels: bug, duplicate
